name: Build, Test and Publish

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Upgrade pip and install requests
      run: python -m pip install --upgrade build requests
    - name: Download the NAIF leapseconds file
      run: python naif_leapseconds/fetch.py
    - name: Set Version
      run: |
        VERSION=$(date -u +%Y.%m.%d)
        sed -i "s/.*version =.*/version = \"$VERSION\"/g" pyproject.toml
    - name: Install naif_leapseconds
      run: pip install .[tests]
    - name: Test naif_leapseconds
      run: pytest .
    - name: Build Source Distribution and Wheel
      run: python -m build --sdist --wheel --outdir dist/ .
    - name: Publish naif_leapseconds to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        attestations: false
        verbose: true
