name: Build and Test

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Upgrade pip and install requests
      run: python -m pip install --upgrade build requests
    - name: Download the NAIF leapseconds file
      run: python naif_leapseconds/fetch.py
    - name: Set Version
      run: |
        VERSION=$(date -u +%Y.%m.%d)
        sed -i "s/.*version =.*/version = \"$VERSION\"/g" pyproject.toml
    - name: Install naif_leapseconds
      run: pip install .[tests]
    - name: Test naif_leapseconds
      run: pytest .
